FROM balenalib/%%BALENA_MACHINE_NAME%%

RUN install_packages network-manager udhcpd

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
ENV UDEV on

ENV app_udhcpd_config=/root/udhcpd.conf

COPY udhcpd.conf /root/
COPY start.sh /root/

CMD ["bash", "/root/start.sh"]

